apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-manager-config  # Add a name for your ConfigMap
  namespace: default         # (Optional) Specify the namespace if needed
data:
  alertmanager.yaml: |       # Specify the key that contains the configuration
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'slack-notifier'

    receivers:
      - name: 'slack-notifier'
        slack_configs:
          - api_url: '<SLACK_WEB_URL>' 
            channel: '#alerts'
            text: "Alert: {{ .CommonAnnotations.summary }} \nDescription: {{ .CommonAnnotations.description }}"
