apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Max number of pods that can be unavailable during the update
      maxSurge: 1        # Max number of new pods that can be scheduled above the desired number of pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: arcs1/flask-app:v4
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health  # Flask app endpoint
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health  # Flask app endpoint
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: MONGO_HOST
          value: "mongo-db"  
        - name: MONGO_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80         # External port to access the service
      targetPort: 5000  # Port on the Flask container
  selector:
    app: my-app
