apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
spec:
  replicas: 1   # desired number of replicas
  selector:
    app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: arcs1/flask-app   # Docker image
        ports:
        - containerPort: 5000    # application's port
